# Part II: Setting Up Corporate CA for Service Mesh

== Task 4 (Optional): Use an external custom Certificate Authority (CA)

This section is optional and you can also use for your own understanding of the procedure to provide corporate CA certs to istio rather than using the auto-created one by the operator. This will be achieved through integration with `cert-manager` and `istio-csr`. Note, although possible to use a Vault in this lab we will use a self-signed CA.

=== Step 1 - Verify issuer of current certificates is `cluster.local`

The current _controlplane_ and _dataplane_ certificates are issued by default `Issuer: O = cluster.local`. Verify this with the following commands:

* Check the issuer of the default service mesh CA certificate (it should be `Issuer: O = cluster.local`)
+
[source,shell,subs=attributes,role=execute]
----
./login-as.sh emma
oc get -o yaml secret istio-ca-secret -n {openshift_cluster_user_name}-prod-istio-system | grep ca-cert | awk '{print $2}' | base64 -d | openssl x509 -noout -text
----

* Check the certificates used in the communication with `istiod`, the Issuer is again `Issuer=O = cluster.local`
+
[source,shell,subs=attributes,role=execute]
----
oc exec "$(oc get pod -l app=istio-ingressgateway -n {openshift_cluster_user_name}-prod-istio-system -o jsonpath={.items..metadata.name} | awk '{print $1}')" -c istio-proxy -n {openshift_cluster_user_name}-prod-istio-system -- openssl s_client -showcerts -connect $(oc get svc istiod-{openshift_cluster_user_name}-production -o jsonpath={.spec.clusterIP}):15012
----

* Checking the certificates used in the POD to POD communications, the Issuer is again `Issuer=O = cluster.local`
+
[source,shell,subs=attributes,role=execute]
----
oc exec "$(oc get pod -l app=travels -n {openshift_cluster_user_name}-prod-travel-agency -o jsonpath={.items..metadata.name})" -c istio-proxy -n {openshift_cluster_user_name}-prod-travel-agency -- openssl s_client -showcerts -connect $(oc -n {openshift_cluster_user_name}-prod-travel-agency get svc cars -o jsonpath={.spec.clusterIP}):8000
----

=== Step 2: Integrate Service Mesh with `cert-manager` and `istio-csr`

The `cert-manager` operator is already installed and per the link:https://docs.openshift.com/container-platform/4.14/service_mesh/v2x/ossm-security.html#ossm-cert-manager-integration-istio_ossm-security[documentation] you will focus the activities to integrate it to the `ServiceMeshControlPlane`.

1. First, create the root cluster issuer for the _Travel Agency_ solution.
* Add the self-signed `Issuer` with a `Certificate` for the CA.
+
[source,shell,subs=attributes,role=execute]
----
./login-as.sh emma

echo "apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-root-issuer
  namespace: cert-manager
spec:
  selfSigned: {}" |oc apply -f -

echo "apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: cert-manager
spec:
  isCA: true
  duration: 21600h # 900d
  secretName: root-ca
  commonName: root-ca.travelagency.com
  subject:
    organizations:
      - travelagency.com
  issuerRef:
    name: selfsigned-root-issuer
    kind: Issuer
    group: cert-manager.io" |oc apply -f -
----

* Create an `Issuer` that uses the above generated CA certificate to issue certs for the `istio-ca`
+
[source,shell,subs=attributes,role=execute]
----
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-ca
spec:
  ca:
    secretName: root-ca
----

2. Secondly, create the `istio-ca` which will be used to issue certificates for the communications in the mesh (note both CA certificates duration have been set to _900 days_)
+
[source,shell,subs=attributes,role=execute]
----
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: {openshift_cluster_user_name}-prod-istio-system
spec:
  isCA: true
  duration: 21600h
  secretName: istio-ca
  commonName: istio-ca.travelagency.com
  subject:
    organizations:
      - travelagency.com
  issuerRef:
    name: root-ca
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: istio-ca
  namespace: {openshift_cluster_user_name}-prod-istio-system
spec:
  ca:
    secretName: istio-ca
----

3. Final step before integration is the installation of the `istio-csr`. *Note:* _istio-csr_ is currently unsupported by Red Hat (there are plans for support in the future) so a community version is currently used via helm chart installation.

* Create the `3-istio-csr.yaml` file to contain the helm chart required configuration values.
+
[source,shell,subs=attributes,role=execute]
----
echo "replicaCount: 2

image:
  repository: quay.io/jetstack/cert-manager-istio-csr
  tag: v0.8.1
  pullSecretName: ""

app:
  certmanager:
    namespace: {openshift_cluster_user_name}-prod-istio-system
    issuer:
      group: cert-manager.io
      kind: Issuer
      name: istio-ca

  controller:
    configmapNamespaceSelector: "maistra.io/member-of={openshift_cluster_user_name}-prod-istio-system"
    leaderElectionNamespace: {openshift_cluster_user_name}-prod-istio-system

  istio:
    namespace: {openshift_cluster_user_name}-prod-istio-system
    revisions: ["basic"]

  server:
    maxCertificateDuration: 5m

  tls:
    certificateDNSNames:
      # This DNS name must be set in the SMCP spec.security.certificateAuthority.cert-manager.address
      - cert-manager-istio-csr.{openshift_cluster_user_name}-prod-istio-system.svc" > 3-istio-csr.yaml
----

* Install the repository and helm chart
+
[source,shell,subs=attributes,role=execute]
----
helm repo add jetstack https://charts.jetstack.io
helm install istio-csr jetstack/cert-manager-istio-csr -n {openshift_cluster_user_name}-prod-istio-system -f cer3-istio-csr.yaml
----

4. Lastly, integrate the `istio-csr` to the `{openshift_cluster_user_name}-production` `ServiceMeshControlPlane` by modifying the security section as follows:
+
[source,shell,subs=attributes]
----
  security:
    certificateAuthority:
      cert-manager:
        address: 'cert-manager-istio-csr.user1-prod-istio-system.svc:443'
      type: cert-manager
    controlPlane:
      mtls: true
    dataPlane:
      automtls: true
      mtls: true
    identity:
      type: ThirdParty
----
+
[source,shell,subs=attributes,role=execute]
----
./login-as.sh emma
./update-prod-smcp-use-istio-csr.sh  user1-prod-istio-system user1-production user1-jaeger-small-production
----

=== Step 3: Verify the certificates used in the _controlplane_ and _dataplane_ are from issuer `issuer=O = travelagency.com.

* Check the certificates used in the communication with istiod, the Issuer should be `issuer=O = travelagency.com, CN = istio-ca.travelagency.com`

[source,shell,subs=attributes,role=execute]
----
oc exec "$(oc get pod -l app=istio-ingressgateway -n user1-prod-istio-system -o jsonpath={.items..metadata.name} | awk '{print $1}')" -c istio-proxy -n user1-prod-istio-system -- openssl s_client -showcerts -connect $(oc get svc istiod-user1-production -o jsonpath={.spec.clusterIP}):15012
----

* Check the certificates used in the POD to POD communications, the Issuer is again Issuer=O = cluster.local
** Restart the _dataplane_ pods to expedite the sidecar proxies picking up the secret changes.
+
[source,shell,subs=attributes,role=execute]
----
oc -n {openshift_cluster_user_name}-prod-travel-control delete pods --all
oc -n {openshift_cluster_user_name}-prod-travel-agency delete pods --all
oc -n {openshift_cluster_user_name}-prod-travel-portal delete pods --all
----

** Verify the issuer is `issuer=O = travelagency.com, CN = istio-ca.travelagency.com`
+
[source,shell,subs=attributes,role=execute]
----
oc exec "$(oc get pod -l app=travels -n user1-prod-travel-agency -o jsonpath={.items..metadata.name})" -c istio-proxy -n user1-prod-travel-agency -- openssl s_client -showcerts -connect $(oc -n user1-prod-travel-agency get svc cars -o jsonpath={.spec.clusterIP}):8000
----

Congratulations!!! You have used your orgnization's -self-signed- CA to secure mesh communications.

=== Step 5: Use the `istio-ca` to also secure external communciations (TODO)
