# Introduction

Welcome to the lab *{lab_name}.*

In this lab you are working as *{openshift_cluster_user_name}*.

## ABOUT THIS LAB

This lab will take you through the use case of the _Travel Agency_ organization which intends to utilize Service Mesh for its _Travel Demo_ application. You will be introduced to techniques of designing a mesh based on real stakeholder requirements and delivering against those from development all the way to production. In addition, it introduces a set of corporate personas with responsibilities and permissions to create and operate the mesh.


## Lab assets

//Before you begin, access your link:https://codeserver-codeserver-{openshift_cluster_user_name}.{openshift_cluster_ingress_domain}[code-server environment,window=_blank] and ensure you have access to the lab assets `ossm-labs`.

// Open a terminal (*`Terminal`* -> *`New Terminal`* from the menu) in the _code-server_ so that you can execute the commands during the labs.

You have a terminal on your right hand side with all the lab assets cloned form the Git repo: link:https://github.com/redhat-gpte-devopsautomation/ossm-labs[ossm-labs,window=_blank]. List your current directory and see if all the assets are available:

[source,shell,subs=attributes,role=execute]
----
ls -la
----

You can go and inspect these resources in this repository at a later stage.

//Although for the labs the assets are made available you can additionally get and inspect these resources at a later stage from the link:https://github.com/redhat-gpte-devopsautomation/ossm-labs[ossm-labs,window=_blank] github repository.

## Use of correct Openshift Namespaces

[IMPORTANT]
====
You will be using a *shared cluster for the development environment!* and the Service Mesh users are also common with access to multiple namespaces. Therefore, it is very important that each participant uses their allocated namespaces. In order to make use of the correct *namespaces* make sure you are accessing those with your allocated user id: *{openshift_cluster_user_name}*

You will have a *dedicated OpenShift cluster for your production environment* and you are going to install a cluster-wide Service Mesh in this environment.
====



