# Introduction

Welcome to the lab *{lab_name}.*

In this lab you are working as *{openshift_cluster_user_name}*.

## ABOUT THIS LAB

This lab will take you through the use case of the _Travel Agency_ organization which intends to utilize Service Mesh for its _Travel Demo_ application. You will be introduced to techniques of designing a mesh based on real stakeholder requirements and delivering against those from development all the way to production. In addition, it introduces a set of corporate personas with responsibilities and permissions to create and operate the mesh.


## Lab assets

//Before you begin, access your link:https://codeserver-codeserver-{openshift_cluster_user_name}.{openshift_cluster_ingress_domain}[code-server environment,window=_blank] and ensure you have access to the lab assets `ossm-labs`.

// Open a terminal (*`Terminal`* -> *`New Terminal`* from the menu) in the _code-server_ so that you can execute the commands during the labs.

You have a terminal on your right hand side with all the lab assets cloned form the Git repo: link:https://github.com/redhat-gpte-devopsautomation/ossm-labs[ossm-labs,window=_blank]. List your current directory and see if all the assets are available:

[source,shell,subs=attributes,role=execute]
----
ls -la
----

You can go and inspect these resources in this repository at a later stage.

//Although for the labs the assets are made available you can additionally get and inspect these resources at a later stage from the link:https://github.com/redhat-gpte-devopsautomation/ossm-labs[ossm-labs,window=_blank] github repository.

## Openshift Cluster Environment

[IMPORTANT]
====
You will be using a *dedicated OpenShift cluster for your development AND production environment* and therefore you are going to install Service Mesh in the multi-tenant mode in your OpenShift environment. 
====



